### ISSUE TITLE
Internal Server Error for external Icinga2 targets

### ISSUE THREAD

**Issue by postwarbreakout** [opsdis/icinga2-exporter#32] opened 2022-03-29 15:59 UTC
Hello,

I have Icinga2 performing checks on several hostnames with .com domains which is working fine. However, I cannot query the metrics from these hosts with the exporter as I am receiving 500 Internal Server Error in Prometheus or upon calling the metrics URL manually.
What I noticed is that the hosts have the format subdomain.domain.com and if I remove the subdomain or simply replace it with a non-existing one, I am able to get a result (icinga2_scrape_duration_seconds). Querying internal hosts with host.domain.local addresses is also working well.

Error in icinga2-exporter.log:

{"timestamp": "2022-03-29T17:55:08.543706Z", "level": "ERROR", "name": "quart.app", "message": "Exception on request GET /metrics", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/dist-packages/quart/app.py\", line 1467, in handle_request\n    return await self.full_dispatch_request(request_context)\n  File \"/usr/local/lib/python3.7/dist-packages/quart/app.py\", line 1492, in full_dispatch_request\n    result = await self.handle_user_exception(error)\n  File \"/usr/local/lib/python3.7/dist-packages/quart/app.py\", line 968, in handle_user_exception\n    raise error\n  File \"/usr/local/lib/python3.7/dist-packages/quart/app.py\", line 1490, in full_dispatch_request\n    result = await self.dispatch_request(request_context)\n  File \"/usr/local/lib/python3.7/dist-packages/quart/app.py\", line 1536, in dispatch_request\n    return await self.ensure_async(handler)(**request_.view_args)\n  File \"/usr/local/lib/python3.7/dist-packages/icinga2_exporter/proxy.py\", line 55, in get_metrics\n    await fetch_metadata_task\n  File \"/usr/local/lib/python3.7/dist-packages/icinga2_exporter/perfdata.py\", line 133, in get_host_metrics\n    labels.update(Perfdata.get_host_meta_custom_vars(host_attrs))\n  File \"/usr/local/lib/python3.7/dist-packages/icinga2_exporter/perfdata.py\", line 384, in get_host_meta_custom_vars\n    labels[custom_vars_key.lower()] = Perfdata.valid_prometheus_label_values(custom_vars_value)\n  File \"/usr/local/lib/python3.7/dist-packages/icinga2_exporter/perfdata.py\", line 391, in valid_prometheus_label_values\n    if '\\\\' in value:\nTypeError: argument of type 'int' is not iterable"}

**Comment by thenodon** [comment] 2022-03-30 05:23
Hi @postwarbreakout and thanks for issue report. Im not sure that the issue is related to the hostname. The exception happen when host vars is being transformed to labels. In that logic if the host var include a \ it will be quoted. In your case the host var seems to be a int and doing `value = value.replace('\\', '\\\\')` will cause the exception. This is still a bug since the code should check if the host var is a string before the replace is done.
Can share your host vars for a host that is failing so I can verify that this may be the problem?

**Comment by postwarbreakout** [comment] 2022-04-05 10:23
Hi, do you mean the host configuration? Because it's super basic:

object Host "my.url.com" {
  import "generic-dummy-host"
  address = "my.url.com"
}

**Comment by thenodon** [comment] 2022-04-05 11:27
You can take a screenshot of some of host that is failing so I can see if they have any vars. What would support my assumption is that the vars has a value that is not a string.

**Comment by thenodon** [comment] 2022-04-17 07:16
Close with lack of input. But should be fixed in #33

**Closed by thenodon** 2022-04-17 07:16 UTC

**Comment by postwarbreakout** [comment] 2022-04-20 09:44
I'm sorry, I was on vacation during your last request and forgot to reply. Can confirm that the update fixed the issue.

**Comment by thenodon** [comment] 2022-04-20 11:04
Great to here that it resolved your problem.
